# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MUKit_Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for MUKit_Example
  pod 'MUKit', :path  => '../../MUKit'#本地路径
  #pod 'MUKit'
pod 'AFNetworking'
pod 'SDWebImage'
end
